/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JpRouteImport } from './routes/jp'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JpIndexRouteImport } from './routes/jp.index'
import { Route as JpSignupRouteImport } from './routes/jp.signup'
import { Route as JpLoginRouteImport } from './routes/jp.login'
import { Route as JpContatoRouteImport } from './routes/jp.contato'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JpRoute = JpRouteImport.update({
  id: '/jp',
  path: '/jp',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JpIndexRoute = JpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JpRoute,
} as any)
const JpSignupRoute = JpSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => JpRoute,
} as any)
const JpLoginRoute = JpLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => JpRoute,
} as any)
const JpContatoRoute = JpContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => JpRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/jp': typeof JpRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/jp/contato': typeof JpContatoRoute
  '/jp/login': typeof JpLoginRoute
  '/jp/signup': typeof JpSignupRoute
  '/jp/': typeof JpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/jp/contato': typeof JpContatoRoute
  '/jp/login': typeof JpLoginRoute
  '/jp/signup': typeof JpSignupRoute
  '/jp': typeof JpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/jp': typeof JpRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/jp/contato': typeof JpContatoRoute
  '/jp/login': typeof JpLoginRoute
  '/jp/signup': typeof JpSignupRoute
  '/jp/': typeof JpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/jp'
    | '/login'
    | '/signup'
    | '/jp/contato'
    | '/jp/login'
    | '/jp/signup'
    | '/jp/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/login'
    | '/signup'
    | '/jp/contato'
    | '/jp/login'
    | '/jp/signup'
    | '/jp'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/jp'
    | '/login'
    | '/signup'
    | '/jp/contato'
    | '/jp/login'
    | '/jp/signup'
    | '/jp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  JpRoute: typeof JpRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jp': {
      id: '/jp'
      path: '/jp'
      fullPath: '/jp'
      preLoaderRoute: typeof JpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jp/': {
      id: '/jp/'
      path: '/'
      fullPath: '/jp/'
      preLoaderRoute: typeof JpIndexRouteImport
      parentRoute: typeof JpRoute
    }
    '/jp/signup': {
      id: '/jp/signup'
      path: '/signup'
      fullPath: '/jp/signup'
      preLoaderRoute: typeof JpSignupRouteImport
      parentRoute: typeof JpRoute
    }
    '/jp/login': {
      id: '/jp/login'
      path: '/login'
      fullPath: '/jp/login'
      preLoaderRoute: typeof JpLoginRouteImport
      parentRoute: typeof JpRoute
    }
    '/jp/contato': {
      id: '/jp/contato'
      path: '/contato'
      fullPath: '/jp/contato'
      preLoaderRoute: typeof JpContatoRouteImport
      parentRoute: typeof JpRoute
    }
  }
}

interface JpRouteChildren {
  JpContatoRoute: typeof JpContatoRoute
  JpLoginRoute: typeof JpLoginRoute
  JpSignupRoute: typeof JpSignupRoute
  JpIndexRoute: typeof JpIndexRoute
}

const JpRouteChildren: JpRouteChildren = {
  JpContatoRoute: JpContatoRoute,
  JpLoginRoute: JpLoginRoute,
  JpSignupRoute: JpSignupRoute,
  JpIndexRoute: JpIndexRoute,
}

const JpRouteWithChildren = JpRoute._addFileChildren(JpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  JpRoute: JpRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
