/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PtbrIndexRouteImport } from './routes/ptbr.index'
import { Route as JpIndexRouteImport } from './routes/jp.index'
import { Route as PtbrTermsRouteImport } from './routes/ptbr.terms'
import { Route as PtbrSignupRouteImport } from './routes/ptbr.signup'
import { Route as PtbrPrivacyRouteImport } from './routes/ptbr.privacy'
import { Route as PtbrLoginRouteImport } from './routes/ptbr.login'
import { Route as PtbrContactRouteImport } from './routes/ptbr.contact'
import { Route as JpSplatRouteImport } from './routes/jp.$'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCreditsRouteImport } from './routes/_authenticated/credits'
import { Route as AuthenticatedCompleteProfileRouteImport } from './routes/_authenticated/complete-profile'
import { Route as AuthenticatedLessonsIndexRouteImport } from './routes/_authenticated/lessons.index'
import { Route as AuthenticatedTeacherScheduleRouteImport } from './routes/_authenticated/teacher.schedule'
import { Route as AuthenticatedTeacherProfileRouteImport } from './routes/_authenticated/teacher.profile'
import { Route as AuthenticatedTeacherLessonsRouteImport } from './routes/_authenticated/teacher.lessons'
import { Route as AuthenticatedTeacherDashboardRouteImport } from './routes/_authenticated/teacher.dashboard'
import { Route as AuthenticatedTeacherProfileIdRouteImport } from './routes/_authenticated/teacher-profile.$id'
import { Route as AuthenticatedPtbrScheduleRouteImport } from './routes/_authenticated/ptbr.schedule'
import { Route as AuthenticatedPtbrProfileRouteImport } from './routes/_authenticated/ptbr.profile'
import { Route as AuthenticatedPtbrDashboardRouteImport } from './routes/_authenticated/ptbr.dashboard'
import { Route as AuthenticatedPtbrCreditsRouteImport } from './routes/_authenticated/ptbr.credits'
import { Route as AuthenticatedPtbrCompleteProfileRouteImport } from './routes/_authenticated/ptbr.complete-profile'
import { Route as AuthenticatedLessonsIdRouteImport } from './routes/_authenticated/lessons.$id'
import { Route as AuthenticatedCheckoutReturnRouteImport } from './routes/_authenticated/checkout.return'
import { Route as AuthenticatedTeacherStudentsIndexRouteImport } from './routes/_authenticated/teacher.students.index'
import { Route as AuthenticatedPtbrLessonsIndexRouteImport } from './routes/_authenticated/ptbr.lessons.index'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedTeacherStudentsIdRouteImport } from './routes/_authenticated/teacher.students.$id'
import { Route as AuthenticatedPtbrTeacherProfileIdRouteImport } from './routes/_authenticated/ptbr.teacher-profile.$id'
import { Route as AuthenticatedPtbrLessonsIdRouteImport } from './routes/_authenticated/ptbr.lessons.$id'
import { Route as AuthenticatedPtbrCheckoutReturnRouteImport } from './routes/_authenticated/ptbr.checkout.return'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PtbrIndexRoute = PtbrIndexRouteImport.update({
  id: '/ptbr/',
  path: '/ptbr/',
  getParentRoute: () => rootRouteImport,
} as any)
const JpIndexRoute = JpIndexRouteImport.update({
  id: '/jp/',
  path: '/jp/',
  getParentRoute: () => rootRouteImport,
} as any)
const PtbrTermsRoute = PtbrTermsRouteImport.update({
  id: '/ptbr/terms',
  path: '/ptbr/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PtbrSignupRoute = PtbrSignupRouteImport.update({
  id: '/ptbr/signup',
  path: '/ptbr/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PtbrPrivacyRoute = PtbrPrivacyRouteImport.update({
  id: '/ptbr/privacy',
  path: '/ptbr/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PtbrLoginRoute = PtbrLoginRouteImport.update({
  id: '/ptbr/login',
  path: '/ptbr/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PtbrContactRoute = PtbrContactRouteImport.update({
  id: '/ptbr/contact',
  path: '/ptbr/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const JpSplatRoute = JpSplatRouteImport.update({
  id: '/jp/$',
  path: '/jp/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreditsRoute = AuthenticatedCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompleteProfileRoute =
  AuthenticatedCompleteProfileRouteImport.update({
    id: '/complete-profile',
    path: '/complete-profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLessonsIndexRoute =
  AuthenticatedLessonsIndexRouteImport.update({
    id: '/lessons/',
    path: '/lessons/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherScheduleRoute =
  AuthenticatedTeacherScheduleRouteImport.update({
    id: '/teacher/schedule',
    path: '/teacher/schedule',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherProfileRoute =
  AuthenticatedTeacherProfileRouteImport.update({
    id: '/teacher/profile',
    path: '/teacher/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherLessonsRoute =
  AuthenticatedTeacherLessonsRouteImport.update({
    id: '/teacher/lessons',
    path: '/teacher/lessons',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherDashboardRoute =
  AuthenticatedTeacherDashboardRouteImport.update({
    id: '/teacher/dashboard',
    path: '/teacher/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherProfileIdRoute =
  AuthenticatedTeacherProfileIdRouteImport.update({
    id: '/teacher-profile/$id',
    path: '/teacher-profile/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPtbrScheduleRoute =
  AuthenticatedPtbrScheduleRouteImport.update({
    id: '/ptbr/schedule',
    path: '/ptbr/schedule',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPtbrProfileRoute =
  AuthenticatedPtbrProfileRouteImport.update({
    id: '/ptbr/profile',
    path: '/ptbr/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPtbrDashboardRoute =
  AuthenticatedPtbrDashboardRouteImport.update({
    id: '/ptbr/dashboard',
    path: '/ptbr/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPtbrCreditsRoute =
  AuthenticatedPtbrCreditsRouteImport.update({
    id: '/ptbr/credits',
    path: '/ptbr/credits',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPtbrCompleteProfileRoute =
  AuthenticatedPtbrCompleteProfileRouteImport.update({
    id: '/ptbr/complete-profile',
    path: '/ptbr/complete-profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLessonsIdRoute = AuthenticatedLessonsIdRouteImport.update({
  id: '/lessons/$id',
  path: '/lessons/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutReturnRoute =
  AuthenticatedCheckoutReturnRouteImport.update({
    id: '/checkout/return',
    path: '/checkout/return',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherStudentsIndexRoute =
  AuthenticatedTeacherStudentsIndexRouteImport.update({
    id: '/teacher/students/',
    path: '/teacher/students/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPtbrLessonsIndexRoute =
  AuthenticatedPtbrLessonsIndexRouteImport.update({
    id: '/ptbr/lessons/',
    path: '/ptbr/lessons/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTeacherStudentsIdRoute =
  AuthenticatedTeacherStudentsIdRouteImport.update({
    id: '/teacher/students/$id',
    path: '/teacher/students/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPtbrTeacherProfileIdRoute =
  AuthenticatedPtbrTeacherProfileIdRouteImport.update({
    id: '/ptbr/teacher-profile/$id',
    path: '/ptbr/teacher-profile/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPtbrLessonsIdRoute =
  AuthenticatedPtbrLessonsIdRouteImport.update({
    id: '/ptbr/lessons/$id',
    path: '/ptbr/lessons/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPtbrCheckoutReturnRoute =
  AuthenticatedPtbrCheckoutReturnRouteImport.update({
    id: '/ptbr/checkout/return',
    path: '/ptbr/checkout/return',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/complete-profile': typeof AuthenticatedCompleteProfileRoute
  '/credits': typeof AuthenticatedCreditsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/jp/$': typeof JpSplatRoute
  '/ptbr/contact': typeof PtbrContactRoute
  '/ptbr/login': typeof PtbrLoginRoute
  '/ptbr/privacy': typeof PtbrPrivacyRoute
  '/ptbr/signup': typeof PtbrSignupRoute
  '/ptbr/terms': typeof PtbrTermsRoute
  '/jp/': typeof JpIndexRoute
  '/ptbr/': typeof PtbrIndexRoute
  '/checkout/return': typeof AuthenticatedCheckoutReturnRoute
  '/lessons/$id': typeof AuthenticatedLessonsIdRoute
  '/ptbr/complete-profile': typeof AuthenticatedPtbrCompleteProfileRoute
  '/ptbr/credits': typeof AuthenticatedPtbrCreditsRoute
  '/ptbr/dashboard': typeof AuthenticatedPtbrDashboardRoute
  '/ptbr/profile': typeof AuthenticatedPtbrProfileRoute
  '/ptbr/schedule': typeof AuthenticatedPtbrScheduleRoute
  '/teacher-profile/$id': typeof AuthenticatedTeacherProfileIdRoute
  '/teacher/dashboard': typeof AuthenticatedTeacherDashboardRoute
  '/teacher/lessons': typeof AuthenticatedTeacherLessonsRoute
  '/teacher/profile': typeof AuthenticatedTeacherProfileRoute
  '/teacher/schedule': typeof AuthenticatedTeacherScheduleRoute
  '/lessons/': typeof AuthenticatedLessonsIndexRoute
  '/ptbr/checkout/return': typeof AuthenticatedPtbrCheckoutReturnRoute
  '/ptbr/lessons/$id': typeof AuthenticatedPtbrLessonsIdRoute
  '/ptbr/teacher-profile/$id': typeof AuthenticatedPtbrTeacherProfileIdRoute
  '/teacher/students/$id': typeof AuthenticatedTeacherStudentsIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/ptbr/lessons/': typeof AuthenticatedPtbrLessonsIndexRoute
  '/teacher/students/': typeof AuthenticatedTeacherStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/complete-profile': typeof AuthenticatedCompleteProfileRoute
  '/credits': typeof AuthenticatedCreditsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/jp/$': typeof JpSplatRoute
  '/ptbr/contact': typeof PtbrContactRoute
  '/ptbr/login': typeof PtbrLoginRoute
  '/ptbr/privacy': typeof PtbrPrivacyRoute
  '/ptbr/signup': typeof PtbrSignupRoute
  '/ptbr/terms': typeof PtbrTermsRoute
  '/jp': typeof JpIndexRoute
  '/ptbr': typeof PtbrIndexRoute
  '/checkout/return': typeof AuthenticatedCheckoutReturnRoute
  '/lessons/$id': typeof AuthenticatedLessonsIdRoute
  '/ptbr/complete-profile': typeof AuthenticatedPtbrCompleteProfileRoute
  '/ptbr/credits': typeof AuthenticatedPtbrCreditsRoute
  '/ptbr/dashboard': typeof AuthenticatedPtbrDashboardRoute
  '/ptbr/profile': typeof AuthenticatedPtbrProfileRoute
  '/ptbr/schedule': typeof AuthenticatedPtbrScheduleRoute
  '/teacher-profile/$id': typeof AuthenticatedTeacherProfileIdRoute
  '/teacher/dashboard': typeof AuthenticatedTeacherDashboardRoute
  '/teacher/lessons': typeof AuthenticatedTeacherLessonsRoute
  '/teacher/profile': typeof AuthenticatedTeacherProfileRoute
  '/teacher/schedule': typeof AuthenticatedTeacherScheduleRoute
  '/lessons': typeof AuthenticatedLessonsIndexRoute
  '/ptbr/checkout/return': typeof AuthenticatedPtbrCheckoutReturnRoute
  '/ptbr/lessons/$id': typeof AuthenticatedPtbrLessonsIdRoute
  '/ptbr/teacher-profile/$id': typeof AuthenticatedPtbrTeacherProfileIdRoute
  '/teacher/students/$id': typeof AuthenticatedTeacherStudentsIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/ptbr/lessons': typeof AuthenticatedPtbrLessonsIndexRoute
  '/teacher/students': typeof AuthenticatedTeacherStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/complete-profile': typeof AuthenticatedCompleteProfileRoute
  '/_authenticated/credits': typeof AuthenticatedCreditsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/jp/$': typeof JpSplatRoute
  '/ptbr/contact': typeof PtbrContactRoute
  '/ptbr/login': typeof PtbrLoginRoute
  '/ptbr/privacy': typeof PtbrPrivacyRoute
  '/ptbr/signup': typeof PtbrSignupRoute
  '/ptbr/terms': typeof PtbrTermsRoute
  '/jp/': typeof JpIndexRoute
  '/ptbr/': typeof PtbrIndexRoute
  '/_authenticated/checkout/return': typeof AuthenticatedCheckoutReturnRoute
  '/_authenticated/lessons/$id': typeof AuthenticatedLessonsIdRoute
  '/_authenticated/ptbr/complete-profile': typeof AuthenticatedPtbrCompleteProfileRoute
  '/_authenticated/ptbr/credits': typeof AuthenticatedPtbrCreditsRoute
  '/_authenticated/ptbr/dashboard': typeof AuthenticatedPtbrDashboardRoute
  '/_authenticated/ptbr/profile': typeof AuthenticatedPtbrProfileRoute
  '/_authenticated/ptbr/schedule': typeof AuthenticatedPtbrScheduleRoute
  '/_authenticated/teacher-profile/$id': typeof AuthenticatedTeacherProfileIdRoute
  '/_authenticated/teacher/dashboard': typeof AuthenticatedTeacherDashboardRoute
  '/_authenticated/teacher/lessons': typeof AuthenticatedTeacherLessonsRoute
  '/_authenticated/teacher/profile': typeof AuthenticatedTeacherProfileRoute
  '/_authenticated/teacher/schedule': typeof AuthenticatedTeacherScheduleRoute
  '/_authenticated/lessons/': typeof AuthenticatedLessonsIndexRoute
  '/_authenticated/ptbr/checkout/return': typeof AuthenticatedPtbrCheckoutReturnRoute
  '/_authenticated/ptbr/lessons/$id': typeof AuthenticatedPtbrLessonsIdRoute
  '/_authenticated/ptbr/teacher-profile/$id': typeof AuthenticatedPtbrTeacherProfileIdRoute
  '/_authenticated/teacher/students/$id': typeof AuthenticatedTeacherStudentsIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/_authenticated/ptbr/lessons/': typeof AuthenticatedPtbrLessonsIndexRoute
  '/_authenticated/teacher/students/': typeof AuthenticatedTeacherStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/complete-profile'
    | '/credits'
    | '/dashboard'
    | '/profile'
    | '/schedule'
    | '/jp/$'
    | '/ptbr/contact'
    | '/ptbr/login'
    | '/ptbr/privacy'
    | '/ptbr/signup'
    | '/ptbr/terms'
    | '/jp/'
    | '/ptbr/'
    | '/checkout/return'
    | '/lessons/$id'
    | '/ptbr/complete-profile'
    | '/ptbr/credits'
    | '/ptbr/dashboard'
    | '/ptbr/profile'
    | '/ptbr/schedule'
    | '/teacher-profile/$id'
    | '/teacher/dashboard'
    | '/teacher/lessons'
    | '/teacher/profile'
    | '/teacher/schedule'
    | '/lessons/'
    | '/ptbr/checkout/return'
    | '/ptbr/lessons/$id'
    | '/ptbr/teacher-profile/$id'
    | '/teacher/students/$id'
    | '/api/public/payments/webhook'
    | '/ptbr/lessons/'
    | '/teacher/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/complete-profile'
    | '/credits'
    | '/dashboard'
    | '/profile'
    | '/schedule'
    | '/jp/$'
    | '/ptbr/contact'
    | '/ptbr/login'
    | '/ptbr/privacy'
    | '/ptbr/signup'
    | '/ptbr/terms'
    | '/jp'
    | '/ptbr'
    | '/checkout/return'
    | '/lessons/$id'
    | '/ptbr/complete-profile'
    | '/ptbr/credits'
    | '/ptbr/dashboard'
    | '/ptbr/profile'
    | '/ptbr/schedule'
    | '/teacher-profile/$id'
    | '/teacher/dashboard'
    | '/teacher/lessons'
    | '/teacher/profile'
    | '/teacher/schedule'
    | '/lessons'
    | '/ptbr/checkout/return'
    | '/ptbr/lessons/$id'
    | '/ptbr/teacher-profile/$id'
    | '/teacher/students/$id'
    | '/api/public/payments/webhook'
    | '/ptbr/lessons'
    | '/teacher/students'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/_authenticated/complete-profile'
    | '/_authenticated/credits'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/schedule'
    | '/jp/$'
    | '/ptbr/contact'
    | '/ptbr/login'
    | '/ptbr/privacy'
    | '/ptbr/signup'
    | '/ptbr/terms'
    | '/jp/'
    | '/ptbr/'
    | '/_authenticated/checkout/return'
    | '/_authenticated/lessons/$id'
    | '/_authenticated/ptbr/complete-profile'
    | '/_authenticated/ptbr/credits'
    | '/_authenticated/ptbr/dashboard'
    | '/_authenticated/ptbr/profile'
    | '/_authenticated/ptbr/schedule'
    | '/_authenticated/teacher-profile/$id'
    | '/_authenticated/teacher/dashboard'
    | '/_authenticated/teacher/lessons'
    | '/_authenticated/teacher/profile'
    | '/_authenticated/teacher/schedule'
    | '/_authenticated/lessons/'
    | '/_authenticated/ptbr/checkout/return'
    | '/_authenticated/ptbr/lessons/$id'
    | '/_authenticated/ptbr/teacher-profile/$id'
    | '/_authenticated/teacher/students/$id'
    | '/api/public/payments/webhook'
    | '/_authenticated/ptbr/lessons/'
    | '/_authenticated/teacher/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  JpSplatRoute: typeof JpSplatRoute
  PtbrContactRoute: typeof PtbrContactRoute
  PtbrLoginRoute: typeof PtbrLoginRoute
  PtbrPrivacyRoute: typeof PtbrPrivacyRoute
  PtbrSignupRoute: typeof PtbrSignupRoute
  PtbrTermsRoute: typeof PtbrTermsRoute
  JpIndexRoute: typeof JpIndexRoute
  PtbrIndexRoute: typeof PtbrIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ptbr/': {
      id: '/ptbr/'
      path: '/ptbr'
      fullPath: '/ptbr/'
      preLoaderRoute: typeof PtbrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jp/': {
      id: '/jp/'
      path: '/jp'
      fullPath: '/jp/'
      preLoaderRoute: typeof JpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ptbr/terms': {
      id: '/ptbr/terms'
      path: '/ptbr/terms'
      fullPath: '/ptbr/terms'
      preLoaderRoute: typeof PtbrTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ptbr/signup': {
      id: '/ptbr/signup'
      path: '/ptbr/signup'
      fullPath: '/ptbr/signup'
      preLoaderRoute: typeof PtbrSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ptbr/privacy': {
      id: '/ptbr/privacy'
      path: '/ptbr/privacy'
      fullPath: '/ptbr/privacy'
      preLoaderRoute: typeof PtbrPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ptbr/login': {
      id: '/ptbr/login'
      path: '/ptbr/login'
      fullPath: '/ptbr/login'
      preLoaderRoute: typeof PtbrLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ptbr/contact': {
      id: '/ptbr/contact'
      path: '/ptbr/contact'
      fullPath: '/ptbr/contact'
      preLoaderRoute: typeof PtbrContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jp/$': {
      id: '/jp/$'
      path: '/jp/$'
      fullPath: '/jp/$'
      preLoaderRoute: typeof JpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/credits': {
      id: '/_authenticated/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof AuthenticatedCreditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/complete-profile': {
      id: '/_authenticated/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof AuthenticatedCompleteProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lessons/': {
      id: '/_authenticated/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof AuthenticatedLessonsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/schedule': {
      id: '/_authenticated/teacher/schedule'
      path: '/teacher/schedule'
      fullPath: '/teacher/schedule'
      preLoaderRoute: typeof AuthenticatedTeacherScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/profile': {
      id: '/_authenticated/teacher/profile'
      path: '/teacher/profile'
      fullPath: '/teacher/profile'
      preLoaderRoute: typeof AuthenticatedTeacherProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/lessons': {
      id: '/_authenticated/teacher/lessons'
      path: '/teacher/lessons'
      fullPath: '/teacher/lessons'
      preLoaderRoute: typeof AuthenticatedTeacherLessonsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/dashboard': {
      id: '/_authenticated/teacher/dashboard'
      path: '/teacher/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof AuthenticatedTeacherDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher-profile/$id': {
      id: '/_authenticated/teacher-profile/$id'
      path: '/teacher-profile/$id'
      fullPath: '/teacher-profile/$id'
      preLoaderRoute: typeof AuthenticatedTeacherProfileIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ptbr/schedule': {
      id: '/_authenticated/ptbr/schedule'
      path: '/ptbr/schedule'
      fullPath: '/ptbr/schedule'
      preLoaderRoute: typeof AuthenticatedPtbrScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ptbr/profile': {
      id: '/_authenticated/ptbr/profile'
      path: '/ptbr/profile'
      fullPath: '/ptbr/profile'
      preLoaderRoute: typeof AuthenticatedPtbrProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ptbr/dashboard': {
      id: '/_authenticated/ptbr/dashboard'
      path: '/ptbr/dashboard'
      fullPath: '/ptbr/dashboard'
      preLoaderRoute: typeof AuthenticatedPtbrDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ptbr/credits': {
      id: '/_authenticated/ptbr/credits'
      path: '/ptbr/credits'
      fullPath: '/ptbr/credits'
      preLoaderRoute: typeof AuthenticatedPtbrCreditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ptbr/complete-profile': {
      id: '/_authenticated/ptbr/complete-profile'
      path: '/ptbr/complete-profile'
      fullPath: '/ptbr/complete-profile'
      preLoaderRoute: typeof AuthenticatedPtbrCompleteProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lessons/$id': {
      id: '/_authenticated/lessons/$id'
      path: '/lessons/$id'
      fullPath: '/lessons/$id'
      preLoaderRoute: typeof AuthenticatedLessonsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout/return': {
      id: '/_authenticated/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof AuthenticatedCheckoutReturnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/students/': {
      id: '/_authenticated/teacher/students/'
      path: '/teacher/students'
      fullPath: '/teacher/students/'
      preLoaderRoute: typeof AuthenticatedTeacherStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ptbr/lessons/': {
      id: '/_authenticated/ptbr/lessons/'
      path: '/ptbr/lessons'
      fullPath: '/ptbr/lessons/'
      preLoaderRoute: typeof AuthenticatedPtbrLessonsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teacher/students/$id': {
      id: '/_authenticated/teacher/students/$id'
      path: '/teacher/students/$id'
      fullPath: '/teacher/students/$id'
      preLoaderRoute: typeof AuthenticatedTeacherStudentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ptbr/teacher-profile/$id': {
      id: '/_authenticated/ptbr/teacher-profile/$id'
      path: '/ptbr/teacher-profile/$id'
      fullPath: '/ptbr/teacher-profile/$id'
      preLoaderRoute: typeof AuthenticatedPtbrTeacherProfileIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ptbr/lessons/$id': {
      id: '/_authenticated/ptbr/lessons/$id'
      path: '/ptbr/lessons/$id'
      fullPath: '/ptbr/lessons/$id'
      preLoaderRoute: typeof AuthenticatedPtbrLessonsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ptbr/checkout/return': {
      id: '/_authenticated/ptbr/checkout/return'
      path: '/ptbr/checkout/return'
      fullPath: '/ptbr/checkout/return'
      preLoaderRoute: typeof AuthenticatedPtbrCheckoutReturnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCompleteProfileRoute: typeof AuthenticatedCompleteProfileRoute
  AuthenticatedCreditsRoute: typeof AuthenticatedCreditsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedCheckoutReturnRoute: typeof AuthenticatedCheckoutReturnRoute
  AuthenticatedLessonsIdRoute: typeof AuthenticatedLessonsIdRoute
  AuthenticatedPtbrCompleteProfileRoute: typeof AuthenticatedPtbrCompleteProfileRoute
  AuthenticatedPtbrCreditsRoute: typeof AuthenticatedPtbrCreditsRoute
  AuthenticatedPtbrDashboardRoute: typeof AuthenticatedPtbrDashboardRoute
  AuthenticatedPtbrProfileRoute: typeof AuthenticatedPtbrProfileRoute
  AuthenticatedPtbrScheduleRoute: typeof AuthenticatedPtbrScheduleRoute
  AuthenticatedTeacherProfileIdRoute: typeof AuthenticatedTeacherProfileIdRoute
  AuthenticatedTeacherDashboardRoute: typeof AuthenticatedTeacherDashboardRoute
  AuthenticatedTeacherLessonsRoute: typeof AuthenticatedTeacherLessonsRoute
  AuthenticatedTeacherProfileRoute: typeof AuthenticatedTeacherProfileRoute
  AuthenticatedTeacherScheduleRoute: typeof AuthenticatedTeacherScheduleRoute
  AuthenticatedLessonsIndexRoute: typeof AuthenticatedLessonsIndexRoute
  AuthenticatedPtbrCheckoutReturnRoute: typeof AuthenticatedPtbrCheckoutReturnRoute
  AuthenticatedPtbrLessonsIdRoute: typeof AuthenticatedPtbrLessonsIdRoute
  AuthenticatedPtbrTeacherProfileIdRoute: typeof AuthenticatedPtbrTeacherProfileIdRoute
  AuthenticatedTeacherStudentsIdRoute: typeof AuthenticatedTeacherStudentsIdRoute
  AuthenticatedPtbrLessonsIndexRoute: typeof AuthenticatedPtbrLessonsIndexRoute
  AuthenticatedTeacherStudentsIndexRoute: typeof AuthenticatedTeacherStudentsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCompleteProfileRoute: AuthenticatedCompleteProfileRoute,
  AuthenticatedCreditsRoute: AuthenticatedCreditsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedCheckoutReturnRoute: AuthenticatedCheckoutReturnRoute,
  AuthenticatedLessonsIdRoute: AuthenticatedLessonsIdRoute,
  AuthenticatedPtbrCompleteProfileRoute: AuthenticatedPtbrCompleteProfileRoute,
  AuthenticatedPtbrCreditsRoute: AuthenticatedPtbrCreditsRoute,
  AuthenticatedPtbrDashboardRoute: AuthenticatedPtbrDashboardRoute,
  AuthenticatedPtbrProfileRoute: AuthenticatedPtbrProfileRoute,
  AuthenticatedPtbrScheduleRoute: AuthenticatedPtbrScheduleRoute,
  AuthenticatedTeacherProfileIdRoute: AuthenticatedTeacherProfileIdRoute,
  AuthenticatedTeacherDashboardRoute: AuthenticatedTeacherDashboardRoute,
  AuthenticatedTeacherLessonsRoute: AuthenticatedTeacherLessonsRoute,
  AuthenticatedTeacherProfileRoute: AuthenticatedTeacherProfileRoute,
  AuthenticatedTeacherScheduleRoute: AuthenticatedTeacherScheduleRoute,
  AuthenticatedLessonsIndexRoute: AuthenticatedLessonsIndexRoute,
  AuthenticatedPtbrCheckoutReturnRoute: AuthenticatedPtbrCheckoutReturnRoute,
  AuthenticatedPtbrLessonsIdRoute: AuthenticatedPtbrLessonsIdRoute,
  AuthenticatedPtbrTeacherProfileIdRoute:
    AuthenticatedPtbrTeacherProfileIdRoute,
  AuthenticatedTeacherStudentsIdRoute: AuthenticatedTeacherStudentsIdRoute,
  AuthenticatedPtbrLessonsIndexRoute: AuthenticatedPtbrLessonsIndexRoute,
  AuthenticatedTeacherStudentsIndexRoute:
    AuthenticatedTeacherStudentsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  JpSplatRoute: JpSplatRoute,
  PtbrContactRoute: PtbrContactRoute,
  PtbrLoginRoute: PtbrLoginRoute,
  PtbrPrivacyRoute: PtbrPrivacyRoute,
  PtbrSignupRoute: PtbrSignupRoute,
  PtbrTermsRoute: PtbrTermsRoute,
  JpIndexRoute: JpIndexRoute,
  PtbrIndexRoute: PtbrIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
